# Generated by Django 6.0.3 on 2026-03-11 06:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelstation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
